name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SETUP_PYTHON_VERSION: '3.10.12'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
      env:
        SETUP_PYTHON_VERSION: '3.10.12'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
      env:
        SETUP_PYTHON_VERSION: '3.10.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python3 -m unittest test.test_expense

    - name: Build a Docker image
      run: docker build -t expense .
